name: Build Release
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:

  create-release:
    name: Create release from this build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Read info
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Generate release changelog
        run: |
          sed -ne '/v1.7.3/,/^## /{/^## /d;p}' CHANGELOG.md |
            sed -e '1d;$d' > CHANGELOG-${{ env.TAG }}.md
      - name: Create (draft) release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          body_path: CHANGELOG-${{ env.TAG }}.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

  deploy-builds:
    needs: [ create-release ]
    strategy:
      matrix:
        arch:
          [
            "linux/amd64 x86_64",
            "linux/arm64/v8 aarch64",
          ]
    name: Build ${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Read info
        id: tags
        shell: bash
        run: |
      - name: Build ${{ matrix.arch }} release
        shell: bash
        run: |
          TAG=${GITHUB_REF#refs/*/}
          arch="${{ matrix.arch }}"
          PLATFORM="${arch%% *}"
          ARCH="${arch##* }"
          docker buildx build --platform $PLATFORM \
            --tag paru:$ARCH \
            --load \
            .
          docker create --name paru-$ARCH paru:$ARCH
          docker cp paru-$ARCH:/app/paru.tar.zst paru-$TAG-$ARCH.tar.zst
      - name: Attach ${{ matrix.arch }} build to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ github.token }}
          file_glob: true
          file: paru-*-*.tar.zst
          tag: ${{ github.ref }}
